version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["gh-dependencies"]
    commit-message:
      prefix: "build(gh)"

  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "monthly"
    labels: ["pip-dependencies"]
    commit-message:
      prefix: "build(pip)"
